package leaseplan.pojo;

import leaseplan.utilities.APIUtils;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;

@Getter
@Setter //These comes from lombok library and autogenerated methods
@ToString
public class Apples {

    public Apples() {
        this.allApples = APIUtils.getAllApples();
    }

    private List<Apple> allApples;



}
