package leaseplan.pojo;

import leaseplan.utilities.APIUtils;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
@Getter
@Setter //These comes from lombok library and autogenerated methods
@ToString
public class Colas {
    public Colas() {
        this.allColas = APIUtils.getAllColas();
    }

    private List<Cola> allColas;

}
