package leaseplan.pojo;

import leaseplan.utilities.APIUtils;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
@Getter
@Setter //These comes from lombok library and autogenerated methods
@ToString
public class Oranges {


    public Oranges() {
        this.allOranges = APIUtils.getAllOrange();
    }

    private List<Orange> allOranges;




}
